-- -----------------------------------------------------------------------------
-- GKE Log Count by Application Service
-- -----------------------------------------------------------------------------
-- Purpose:
-- Counts application log entries generated by each Starfleet service during
-- the last hour.
--
-- This query demonstrates that logs from both the Navigation and
-- Communications services are centralized and can be analyzed independently.
--
-- Source:
-- Dataset: starfleet_gke_logs
-- Table:   stderr
-- -----------------------------------------------------------------------------

SELECT
  CASE
    WHEN resource.labels.pod_name LIKE 'starfleet-navigation-service%'
      THEN 'navigation'
    WHEN resource.labels.pod_name LIKE 'starfleet-communications-service%'
      THEN 'communications'
    ELSE 'other'
  END AS service,
  COUNT(*) AS log_count
FROM
  `starfleet-gke-platform-lab.starfleet_gke_logs.stderr`
WHERE
  timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR)
GROUP BY
  service
ORDER BY
  log_count DESC;
