-- -----------------------------------------------------------------------------
-- GKE Log Count by Cluster
-- -----------------------------------------------------------------------------
-- Purpose:
-- Counts application log entries generated by each GKE cluster during the
-- last hour.
--
-- This query demonstrates that logs from both the Alpha and Delta clusters
-- are being centralized in the same BigQuery dataset.
--
-- Source:
-- Dataset: starfleet_gke_logs
-- Table:   stderr
-- -----------------------------------------------------------------------------

SELECT
  resource.labels.cluster_name AS cluster_name,
  COUNT(*) AS log_count
FROM
  `starfleet-gke-platform-lab.starfleet_gke_logs.stderr`
WHERE
  timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR)
GROUP BY
  cluster_name
ORDER BY
  log_count DESC;
