# -----------------------------------------------------------------------------
# BigQuery Dataset - Centralized GKE Application Logs
# -----------------------------------------------------------------------------
# Stores application logs exported from Google Cloud Logging.
#
# The dataset will contain logs generated by the Starfleet Navigation and
# Communications services running across the Alpha and Delta GKE clusters.
#
# The US multi-region is used because this is a lab environment and both
# clusters are deployed in US regions.
# -----------------------------------------------------------------------------
resource "google_bigquery_dataset" "gke_logs" {
  dataset_id = "starfleet_gke_logs"
  location   = "US"

  description = "Centralized GKE application logs for Starfleet platform lab"

  # Allows Terraform destroy to remove the dataset even when log tables exist.
  # Appropriate for this temporary lab environment.
  delete_contents_on_destroy = true
}


# -----------------------------------------------------------------------------
# Cloud Logging Sink - GKE Application Logs
# -----------------------------------------------------------------------------
# Creates a project-level Logging sink that exports selected Kubernetes
# container logs from Cloud Logging into the BigQuery dataset above.
#
# We intentionally export only our two application workloads instead of all
# GKE system logs. This keeps the BigQuery dataset focused and reduces
# unnecessary log ingestion/storage.
# -----------------------------------------------------------------------------
resource "google_logging_project_sink" "gke_app_logs" {
  name = "starfleet-gke-app-logs"

  # Send matching logs to the BigQuery dataset managed by Terraform.
  destination = "bigquery.googleapis.com/projects/${var.project_id}/datasets/${google_bigquery_dataset.gke_logs.dataset_id}"

  # Select Kubernetes container logs belonging to either Starfleet service.
  # Because this is a project-level sink, matching logs from both Alpha and
  # Delta clusters are included.
  filter = <<EOT
resource.type="k8s_container"
(
  labels.k8s-pod/app="starfleet-navigation-service"
  OR
  labels.k8s-pod/app="starfleet-communications-service"
)
EOT

  # Google creates a dedicated service account identity for this sink.
  # We grant that identity access to the BigQuery dataset below.
  unique_writer_identity = true

  # Creates date-partitioned BigQuery log tables.
  # Partitioning makes time-based queries more efficient and easier to manage.
  bigquery_options {
    use_partitioned_tables = true
  }
}


# -----------------------------------------------------------------------------
# BigQuery IAM - Logging Sink Writer Permission
# -----------------------------------------------------------------------------
# Grants the Cloud Logging sink permission to write exported log entries into
# the Starfleet BigQuery dataset.
#
# The writer identity is generated automatically by the Logging sink because
# unique_writer_identity is enabled above.
# -----------------------------------------------------------------------------
resource "google_bigquery_dataset_iam_member" "logging_sink_writer" {
  dataset_id = google_bigquery_dataset.gke_logs.dataset_id

  # dataEditor provides the sink the permissions required to create/write the
  # BigQuery log tables.
  role = "roles/bigquery.dataEditor"

  # Use the service account identity automatically generated for the sink.
  member = google_logging_project_sink.gke_app_logs.writer_identity
}
